name: Bug Report
description: Report a bug or something that is wrong
title: "[Bug] "
labels: ["bug"]
assignees:
  - MichaelZhao21
body:
  - type: markdown
    attributes: Questionzzzz ask away OwO
  - type: textarea
    id: question
    attributes:
      label: What is your question? Describe in detail.
      description: A clear and concise description of what the question is.
      placeholder: ex. Should this component have [...]
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Put additional context for your question here. This can be screenshots, code, or anything else!